# Пропуск цифр в конфиге, сломает работу плагина.
# Последнее значение в списке определяет максимальный уровень.
# Формат: "1 150" 1 сам уровень, 150 количество опыта для получения этого уровня.
# Добавьте "- none" в "levels" или "hp" для отключения их кастомизации.
levels:
    - 1 150
    - 2 450
    - 3 650
    - 4 850
    - 5 1050
    - 6 1250
    - 7 1550
    - 8 1750
    - 9 1850
    - 10 2050
hp:
    - 0 20
    - 1 20
    - 2 22
    - 3 24
    - 4 26
    - 5 28
    - 6 30
    - 7 32
    - 8 34
    - 9 36
    - 10 40
firstjoin:
# Включение/Выключение функции "Первый заход".
   firstjoin: true
# Изменение опыта и уровня, выдаваемого при первом заходе.
   xp: 0
   lvl: 1
chat:
# Включение/Выключение функции отображения уровня игрока в чате.
   chattag: true
bottle:
# Изменение количества дропа с бутылки опыта.
# Ванильное значение дропа: 3-11 опыта (Измените это на "0" для отключения кастомизации).
    xp: 150
items:
# Измените на "false" для выключения запрета предметов по уровню.
    itemreqlvl: true
# Лор, который нужно проверять ("Требуемый уровень [10]")
    lore: "Требуемый уровень"
pvp:
# ПвП по уровню. 
# "reqpvplvl" Уровень требующийся для возможности вступать в пвп с любыми игроками.
# "diffpvplvl" Цифра, определяющая разницу в опыте. Если разница одного из игроков будет больше, то ПвП будет отменено.
    reqpvplvl: 1
    diffpvplvl: 5
# Измениете на "false" Для выключения не нужных функций.
    funcreqpvplvl: true
    funcdiffpvplvl: true
death:
# Сохранение уровня и опыта при смерте игрока.
# Измените на "false" для выключения сохранения.
    savelvl: true
messages:
# Пропуск после "[XPSystem] " обязателен. Префикс ЗЕЛЕНОГО цвета, сами сообщения БЕЛОГО. 
# Пропуск на конце "lvlup" и "hpup" обязателен (Формат: ...level 1!, ...level 2! и т.д.).
    prefix: "[XPSystem] "
    maxlvl: "Вы достигли максимального уровня!"
    lvlup: "Вы получили новый уровень: "
    hpup: "Количество вашего здоровья увеличено на: "
    maxhp: "Вы достигли максимального количества здоровья!"
    reqlvl: "Вы не имеете требуемый уровень для участия в ПвП! Нужен уровень: "
    reqlvldmg: "У вас и вашей цели слишком большая разница в уровне!"
    itemreqlvl: "Вы недостаточно опытны, чтобы использовать это!"
# Измените на "false" для выключения не нужных сообщений.
    msgmaxlvl: true
    msglvlup: true
    msghpup: true
    msgmaxhp: true
    msgreqlvl: true
    msgitemreqlvl: true
sounds:
# Измените на "false" для отключения звукового оповещения при повышении уровня.
    lvlup: true